version: '3.7'
services:
  pet-shop-s3-connector:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "127.0.0.1:8080:8080"
# bucket name is not set here as localstack malforms the url with pre-signed links
# instead the bucket name is passed into the fileName parameter
# see postman collection for examples
#    environment:
#      - BUCKET_NAME=bucket
    network_mode: host
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3
      - PROVIDER_OVERRIDE_S3=asf
    ports:
      - "4566:4566"
    network_mode: host
    volumes:
      - ./aws:/etc/localstack/init/ready.d
