version: '3.7'
services:
  pet-shop-s3-connector:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - BUCKET_NAME=bucket
    network_mode: host
